[workspace]

members = [
  "dos-rs",
  "macros",

  "examples"
]

# workaround for not getting @PLT
# references to _memset and friends
# which makes the Watcom linker very sad
# using opt-level=1 causes them to be
# inlined
# TODO: create own linker?
[profile.dev]
opt-level = 1
